# Generated by Django 6.0.2 on 2026-02-23 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0002_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.projectmodel'),
        ),
    ]
