# Generated by Django 6.0.2 on 2026-04-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskmodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('In Progress', 'In Progress'), ('Done', 'Done')], max_length=50),
        ),
    ]
